module.exports = {
  REQUESTS: [
    { id: "input", type: "dropdown", initVar: true, applicable: "ynn" },
    { id: "resync", type: "function", applicable: "ynn" },
    { id: "test.pattern", type: "dropdown", applicable: "ynn" },
    { id: "auto.source", type: "dropdown", applicable: "ynn" },
    { id: "edid.mode.hdmi", type: "dropdown", applicable: "ynn" },
    { id: "edid.mode.dp", type: "dropdown", applicable: "ynn" },
    { id: "edid.mode.hdbt", type: "dropdown", applicable: "ynn" },
    { id: "lens.lock", type: "dropdown", applicable: "ynn" },
    { id: "zoom.in", type: "function", applicable: "ynn" },
    { id: "zoom.out", type: "function", applicable: "ynn" },
    { id: "focus.near", type: "function", applicable: "ynn" },
    { id: "focus.far", type: "function", applicable: "ynn" },
    { id: "lens.up", type: "function", applicable: "ynn" },
    { id: "lens.down", type: "function", applicable: "ynn" },
    { id: "lens.left", type: "function", applicable: "ynn" },
    { id: "lens.right", type: "function", applicable: "ynn" },
    { id: "lens.center", type: "function", applicable: "ynn" },
    {
      id: "lens.load",
      type: "range",
      range: [0, 10],
      step: 1,
      applicable: "ynn",
    },
    {
      id: "lens.save",
      type: "range",
      range: [0, 10],
      step: 1,
      applicable: "ynn",
    },
    {
      id: "lens.clear",
      type: "range",
      range: [0, 10],
      step: 1,
      applicable: "ynn",
    },
    { id: "gamma", type: "dropdown", applicable: "ynn" },
    { id: "hdr", type: "dropdown", applicable: "ynn" },
    { id: "brightness", type: "range", range: [0, 200], applicable: "ynn" },
    { id: "contrast", type: "range", range: [0, 200], applicable: "ynn" },
    { id: "saturation", type: "range", range: [0, 200], applicable: "ynn" },
    { id: "hue", type: "range", range: [0, 200], applicable: "ynn" },
    { id: "sharpness", type: "range", range: [0, 10], applicable: "ynn" },
    { id: "nr.level", type: "range", range: [0, 3], applicable: "ynn" },
    { id: "freeze", type: "dropdown", applicable: "ynn" },
    { id: "sp.on", type: "dropdown", applicable: "ynn" },
    { id: "brigh.correction", type: "dropdown", applicable: "ynn" },
    { id: "db.on", type: "dropdown", applicable: "ynn" },
    { id: "light.off.timer", type: "dropdown", applicable: "ynn" },
    { id: "color.space", type: "dropdown", applicable: "ynn" },
    { id: "color.mode", type: "dropdown", applicable: "ynn" },
    { id: "color.max", type: "dropdown", applicable: "ynn" },
    { id: "hsg.hue.r", type: "range", range: [0, 1000], applicable: "ynn" },
    { id: "hsg.hue.g", type: "range", range: [0, 1000], applicable: "ynn" },
    { id: "hsg.hue.b", type: "range", range: [0, 1000], applicable: "ynn" },
    { id: "hsg.hue.c", type: "range", range: [0, 1000], applicable: "ynn" },
    { id: "hsg.hue.m", type: "range", range: [0, 1000], applicable: "ynn" },
    { id: "hsg.hue.y", type: "range", range: [0, 1000], applicable: "ynn" },
    { id: "hsg.sat.r", type: "range", range: [0, 1000], applicable: "ynn" },
    { id: "hsg.sat.g", type: "range", range: [0, 1000], applicable: "ynn" },
    { id: "hsg.sat.b", type: "range", range: [0, 1000], applicable: "ynn" },
    { id: "hsg.sat.c", type: "range", range: [0, 1000], applicable: "ynn" },
    { id: "hsg.sat.m", type: "range", range: [0, 1000], applicable: "ynn" },
    { id: "hsg.sat.y", type: "range", range: [0, 1000], applicable: "ynn" },
    { id: "hsg.gain.r", type: "range", range: [0, 1000], applicable: "ynn" },
    { id: "hsg.gain.g", type: "range", range: [0, 1000], applicable: "ynn" },
    { id: "hsg.gain.b", type: "range", range: [0, 1000], applicable: "ynn" },
    { id: "hsg.gain.c", type: "range", range: [0, 1000], applicable: "ynn" },
    { id: "hsg.gain.m", type: "range", range: [0, 1000], applicable: "ynn" },
    { id: "hsg.gain.y", type: "range", range: [0, 1000], applicable: "ynn" },
    { id: "hsg.white.r", type: "range", range: [0, 1000], applicable: "ynn" },
    { id: "hsg.white.g", type: "range", range: [0, 1000], applicable: "ynn" },
    { id: "hsg.white.b", type: "range", range: [0, 1000], applicable: "ynn" },
    { id: "hsg.reset", type: "function", applicable: "ynn" },
    { id: "red.lift", type: "range", range: [0, 200], applicable: "ynn" },
    { id: "green.lift", type: "range", range: [0, 200], applicable: "ynn" },
    { id: "blue.lift", type: "range", range: [0, 200], applicable: "ynn" },
    { id: "red.gain", type: "range", range: [0, 200], applicable: "ynn" },
    { id: "green.gain", type: "range", range: [0, 200], applicable: "ynn" },
    { id: "blue.gain", type: "range", range: [0, 200], applicable: "ynn" },
    { id: "gainlift.reset", type: "function", applicable: "ynn" },
    { id: "color.temp", type: "dropdown", applicable: "ynn" },
    { id: "aspect.ratio", type: "dropdown", applicable: "ynn" },
    { id: "digi.zoom", type: "range", range: [0, 100], applicable: "ynn" },
    { id: "digi.pan", type: "range", range: [-1280, 1280], applicable: "ynn" },
    { id: "digi.scan", type: "range", range: [-720, 720], applicable: "ynn" },
    { id: "overscan", type: "dropdown", applicable: "ynn" },
    { id: "blanking.top", type: "range", range: [0, 360], applicable: "ynn" },
    {
      id: "blanking.bottom",
      type: "range",
      range: [0, 360],
      applicable: "ynn",
    },
    { id: "blanking.left", type: "range", range: [0, 534], applicable: "ynn" },
    { id: "blanking.right", type: "range", range: [0, 534], applicable: "ynn" },
    { id: "blanking.reset", type: "function", applicable: "ynn" },
    { id: "orientation", type: "dropdown", applicable: "ynn" },
    { id: "altitude", type: "dropdown", applicable: "ynn" },
    { id: "date", type: "text", applicable: "ynn" },
    { id: "time.zone", type: "range", range: [-11, 12], applicable: "ynn" },
    { id: "time.adjust", type: "text", applicable: "ynn" },
    { id: "startup.logo", type: "dropdown", applicable: "ynn" },
    { id: "blank.screen", type: "dropdown", applicable: "ynn" },
    { id: "pic.mute.cfg", type: "dropdown", applicable: "ynn" },
    { id: "smear.reduction", type: "dropdown", applicable: "ynn" },
    { id: "output.framerate", type: "dropdown", applicable: "ynn" },
    { id: "hdmi.eq", type: "dropdown", applicable: "ynn" },
    { id: "laser.cal", type: "dropdown", applicable: "ynn" },
    { id: "screen.setting", type: "dropdown", applicable: "ynn" },
    { id: "screen.position", applicable: "ynn" },
    { id: "auto.poweroff", type: "dropdown", applicable: "ynn" },
    { id: "auto.poweron", type: "dropdown", applicable: "ynn" },
    { id: "schedule.power", type: "dropdown", applicable: "ynn" },
    { id: "schedule1.on.day", applicable: "ynn" },
    { id: "schedule1.off.day", applicable: "ynn" },
    { id: "schedule1.on.time", applicable: "ynn" },
    { id: "schedule1.off.time", applicable: "ynn" },
    { id: "schedule2.on.day", applicable: "ynn" },
    { id: "schedule2.off.day", applicable: "ynn" },
    { id: "schedule2.on.time", applicable: "ynn" },
    { id: "schedule2.off.time", applicable: "ynn" },
    { id: "instant.startup", type: "dropdown", applicable: "ynn" },
    { id: "standby.period", type: "dropdown", applicable: "ynn" },
    { id: "user.std.rx/user.std.ry", applicable: "ynn" },
    { id: "user.std.gx/user.std.gy", applicable: "ynn" },
    { id: "user.std.bx/user.std.by", applicable: "ynn" },
    { id: "user.std.wx/user.std.wy", applicable: "ynn" },
    { id: "user.std.reset", type: "function", applicable: "ynn" },
    { id: "user.target.rx/user.target.ry", applicable: "ynn" },
    { id: "user.target.gx/user.target.gy", applicable: "ynn" },
    { id: "user.target.bx/user.target.by", applicable: "ynn" },
    { id: "user.target.yx/user.target.yy", applicable: "ynn" },
    { id: "user.target.cx/user.target.cy", applicable: "ynn" },
    { id: "user.target.mx/user.target.my", applicable: "ynn" },
    { id: "user.target.wx/user.target.wy", applicable: "ynn" },
    { id: "user.target.reset", type: "function", applicable: "ynn" },
    { id: "user2.target.rx/user2.target.ry", applicable: "ynn" },
    { id: "user2.target.gx/user2.target.gy", applicable: "ynn" },
    { id: "user2.target.bx/user2.target.by", applicable: "ynn" },
    { id: "user2.target.yx/user2.target.yy", applicable: "ynn" },
    { id: "user2.target.cx/user2.target.cy", applicable: "ynn" },
    { id: "user2.target.mx/user2.target.my", applicable: "ynn" },
    { id: "user2.target.wx/user2.target.wy", applicable: "ynn" },
    { id: "user2.target.reset", type: "function", applicable: "ynn" },
    { id: "ir.enable", type: "dropdown", applicable: "ynn" },
    { id: "ir.code", type: "range", range: [0, 99], applicable: "ynn" },
    { id: "ir.code.rst", type: "function", applicable: "ynn" },
    { id: "hotkey1", type: "dropdown", applicable: "ynn" },
    { id: "hotkey2", type: "dropdown", applicable: "ynn" },
    { id: "hotkey3", type: "dropdown", applicable: "ynn" },
    { id: "key.backlight", type: "dropdown", applicable: "ynn" },
    { id: "osd.lang", type: "dropdown", applicable: "yyy" },
    { id: "osd.menupos", type: "dropdown", applicable: "ynn" },
    { id: "osd.timer", type: "dropdown", applicable: "ynn" },
    { id: "osd.rotation", type: "dropdown", applicable: "ynn" },
    { id: "standby.mode", type: "dropdown", applicable: "ynn" },
    { id: "recall.mem", type: "dropdown", applicable: "ynn" },
    { id: "save.mem", type: "dropdown", applicable: "ynn" },
    { id: "osd.pin.enable", type: "dropdown", applicable: "ynn" },
    { id: "osd.pin", type: "range", range: [0, 9999], applicable: "ynn" },
    { id: "osd.pin.reset", type: "function", applicable: "ynn" },
    { id: "model.name", type: "info", applicable: "yyy" },
    { id: "serial", type: "info", applicable: "yyy" },
    { id: "sw.version", type: "info", applicable: "yyy" },
    { id: "sw1.version", type: "info", applicable: "ynn" },
    { id: "sw2.version", type: "info", applicable: "ynn" },
    { id: "sw3.version", type: "info", applicable: "ynn" },
    { id: "laser.hours", type: "info", applicable: "nyn" },
    { id: "ac.voltage", type: "info", applicable: "nyn" },
    { id: "laser.temp", type: "info", applicable: "nyn" },
    { id: "act.source", type: "info" },
    { id: "signal", type: "info", applicable: "ynn" },
    { id: "h.refresh", type: "info", applicable: "ynn" },
    { id: "v.refresh", type: "info", applicable: "ynn" },
    { id: "pixel.clock", type: "info", applicable: "ynn" },
    { id: "color.format", type: "info", applicable: "ynn" },
    { id: "hdr.format", type: "info", applicable: "ynn" },
    { id: "atmos.alti", type: "info", applicable: "ynn" },
    { id: "atmos.pressure", type: "info", applicable: "ynn" },
    { id: "altitude.info", type: "info", applicable: "yyn" },
    { id: "total.hours", type: "info", applicable: "yyn" },
    { id: "laser.power.info", type: "info", applicable: "yyn" },
    { id: "ti", type: "info", applicable: "yyn" },
    { id: "tc.r", type: "info", applicable: "ynn" },
    { id: "tc.g", type: "info", applicable: "ynn" },
    { id: "tc.b", type: "info", applicable: "ynn" },
    { id: "fans", type: "info", applicable: "yyy" },
    { id: "water.pump1", type: "info", applicable: "yyn" },
    { id: "water.pump2", type: "info", applicable: "nyn" },
    { id: "factory.reset", type: "function", applicable: "yyn" },
    { id: "power", type: "dropdown", applicable: "yyy" },
    { id: "pic.mute", type: "dropdown", applicable: "yyn" },
    { id: "status", type: "dropdown", applicable: "yyy" },
    { id: "errcode", type: "info", applicable: "yyy" },
    { id: "err.reset", type: "function", applicable: "yyy" },
    { id: "resolution.x", type: "range", range: [0, 1920], applicable: "ynn" },
    { id: "resolution.y", type: "range", range: [0, 1200], applicable: "ynn" },
    { id: "pj.color", type: "dropdown", applicable: "ynn" },
    { id: "laser.hours", type: "info", applicable: "nyn" },
    { id: "laser.mode", type: "dropdown", applicable: "nyn" },
    { id: "laser.power", type: "range", range: [30, 100], applicable: "nyn" },
    { id: "laser.cbc.enable", type: "dropdown", applicable: "nyn" },
    {
      id: "laser.cbc.target",
      type: "range",
      range: [0, 65535],
      applicable: "nyn",
    },
    { id: "laser.cbc.state", type: "info", applicable: "nyn" },
  ],
  STATUS: [
    { id: 0, label: "Standby" },
    { id: 1, label: "Warm Up" },
    { id: 2, label: "Imaging" },
    { id: 3, label: "Cooling" },
    { id: 4, label: "Warning" },
  ],
  INPUT: [
    { id: 0, label: "HDMI" },
    { id: 1, label: "HDBaseT" },
    { id: 2, label: "DisplayPort" },
  ],
  TEST_PATTERN: [
    { id: 0, label: "Off" },
    { id: 1, label: "White" },
    { id: 2, label: "Black" },
    { id: 3, label: "Red" },
    { id: 4, label: "Green" },
    { id: 5, label: "Blue" },
    { id: 6, label: "Checkboard" },
    { id: 7, label: "CrossHatch" },
    { id: 8, label: "V Burst" },
    { id: 9, label: "H Burst" },
    { id: 10, label: "ColorBar" },
    { id: 11, label: "Plunge" },
  ],
  AUTO_SOURCE: [
    { id: 0, label: "Off" },
    { id: 1, label: "On" },
  ],
  EDID_MODE_HDMI: [
    { id: 0, label: "4K/60 HDR" },
    { id: 1, label: "4K/30" },
    { id: 2, label: "1920x1200p60" },
    { id: 3, label: "1920x1080p60" },
    { id: 4, label: "11280x800p60" },
  ],
  EDID_MODE_DP: [
    { id: 0, label: "4K/60 HDR" },
    { id: 1, label: "4K/30" },
    { id: 2, label: "1920x1200p60" },
    { id: 3, label: "1920x1080p60" },
    { id: 4, label: "11280x800p60" },
  ],
  EDID_MODE_HDBT: [
    { id: 0, label: "4K/30" },
    { id: 1, label: "1920x1200p60" },
    { id: 2, label: "1920x1080p60" },
    { id: 3, label: "11280x800p60" },
  ],
  LENS_LOCK: [
    { id: 0, label: "Off" },
    { id: 1, label: "On" },
  ],
  GAMMA: [
    { id: 0, label: "1.0" },
    { id: 1, label: "1.8" },
    { id: 2, label: "2.0" },
    { id: 3, label: "2.2" },
    { id: 4, label: "2.35" },
    { id: 5, label: "2.5" },
    { id: 6, label: "DICOM" },
  ],
  HDR: [
    { id: 0, label: "Off" },
    { id: 1, label: "Auto" },
    { id: 2, label: "HDR-PQ400" },
    { id: 3, label: "HDR-PQ500" },
    { id: 4, label: "HDR-PQ1000" },
    { id: 5, label: "HDR-HLG" },
  ],
  FREEZE: [
    { id: 0, label: "Off" },
    { id: 1, label: "On" },
  ],
  BRIGH_CORRECTION: [
    { id: 0, label: "Off" },
    { id: 1, label: "BC1" },
    { id: 2, label: "BC2" },
    { id: 3, label: "BC3" },
    { id: 4, label: "BC4" },
    { id: 5, label: "BC5" },
    { id: 6, label: "BC6" },
  ],
  //  DB_ON: [
  //    { id: 0, label: "Off" },
  //    { id: 1, label: "On" },
  //  ],
  LIGHT_OFF_TIMER: [
    { id: 0, label: "Reserved" },
    { id: 1, label: "0.5s" },
    { id: 2, label: "1s" },
    { id: 3, label: "1.5s" },
    { id: 4, label: "2s" },
    { id: 5, label: "3s" },
    { id: 6, label: "4s" },
  ],
  COLOR_SPACE: [
    { id: 0, label: "Auto" },
    { id: 1, label: "YPbPr" },
    { id: 2, label: "YCbCr" },
    { id: 3, label: "RGB-PC" },
    { id: 4, label: "RGB-Video" },
  ],
  COLOR_MODE: [
    { id: 0, label: "ColorMax" },
    { id: 1, label: "Manual Color Matching" },
    { id: 2, label: "Color Temperature" },
    { id: 3, label: "Gains and Lifts" },
  ],
  COLOR_MAX: [
    { id: 0, label: "REC709" },
    { id: 1, label: "Extended" },
    { id: 2, label: "Ultra" },
    { id: 3, label: "Peak" },
    { id: 4, label: "User1" },
    { id: 5, label: "User2" },
  ],
  COLOR_TEMP: [
    { id: 0, label: "3200K" },
    { id: 1, label: "5400K" },
    { id: 2, label: "6500K" },
    { id: 3, label: "7500K" },
    { id: 4, label: "9300K" },
    { id: 5, label: "Native" },
  ],
  ASPECT_RATIO: [
    { id: 0, label: "5:4" },
    { id: 1, label: "4:3" },
    { id: 2, label: "16:10" },
    { id: 3, label: "16:9" },
    { id: 4, label: "1.88" },
    { id: 5, label: "2.35" },
    { id: 6, label: "TheaterScope" },
    { id: 7, label: "Source" },
    { id: 8, label: "Unscaled" },
  ],
  OVERSCAN: [
    { id: 0, label: "Off" },
    { id: 1, label: "Crop" },
    { id: 2, label: "Zoom" },
  ],
  ORIENTATION: [
    { id: 0, label: "Front Tabletop" },
    { id: 1, label: "Front Ceiling" },
    { id: 2, label: "Rear Tabletop" },
    { id: 3, label: "Rear Ceiling" },
    { id: 4, label: "Auto-front" },
  ],
  ALTITUDE: [
    { id: 0, label: "Off" },
    { id: 1, label: "On" },
    { id: 2, label: "Auto" },
    { id: 3, label: "Quiet" },
  ],
  BLANK_SCREEN: [
    { id: 0, label: "Logo" },
    { id: 1, label: "Black" },
    { id: 2, label: "Blue" },
    { id: 3, label: "White" },
  ],
  PIC_MUTE_CFG: [
    { id: 0, label: "DMD Blanking" },
    { id: 1, label: "Laser" },
  ],
  SMEAR_REDUCTION: [
    { id: 0, label: "Off" },
    { id: 1, label: "6ms" },
    { id: 2, label: "7ms" },
    { id: 3, label: "8ms" },
    { id: 4, label: "9ms" },
    { id: 5, label: "10ms" },
  ],
  OUTPUT_FRAMERATE: [
    { id: 0, label: "Auto" },
    { id: 1, label: "48Hz" },
    { id: 2, label: "50Hz" },
    { id: 3, label: "60Hz" },
  ],
  HDMI_EQ: [
    { id: 0, label: "Auto" },
    { id: 1, label: "High" },
    { id: 2, label: "Middle" },
    { id: 3, label: "Low" },
  ],
  LASER_CAL: [
    { id: 0, label: "Disable" },
    { id: 1, label: "Enable" },
  ],
  SCREEN_SETTING: [
    { id: 0, label: "16:10" },
    { id: 1, label: "16:9" },
    { id: 2, label: "4:3" },
    { id: 3, label: "2.35:1" },
  ],
  OSD_LANG: [
    { id: 0, label: "English" },
    { id: 1, label: "French" },
    { id: 2, label: "Spanish" },
    { id: 3, label: "German" },
    { id: 4, label: "NA" },
    { id: 5, label: "Simplified Chinese" },
    { id: 6, label: "Traditional Chinese" },
    { id: 7, label: "Japanese" },
    { id: 8, label: "Korean" },
  ],
  OSD_MENUPOS: [
    { id: 0, label: "Top Left" },
    { id: 1, label: "Top Right" },
    { id: 2, label: "Bottom Left" },
    { id: 3, label: "Bottom Right" },
    { id: 4, label: "Center" },
  ],
  OSD_TIMER: [
    { id: 0, label: "Always On" },
    { id: 1, label: "10 Seconds" },
    { id: 2, label: "30 Seconds" },
    { id: 3, label: "60 Seconds" },
  ],
  OSD_ROTATION: [
    { id: 0, label: "Off" },
    { id: 1, label: "Clockwise" },
    { id: 2, label: "Counterclockwise" },
  ],
  STANDBY_MODE: [
    { id: 0, label: "SuperECO" },
    { id: 1, label: "ECO" },
    { id: 2, label: "Normal" },
  ],
  RECALL_MEM: [
    { id: 0, label: "Preset A" },
    { id: 1, label: "Preset B" },
    { id: 2, label: "Preset C" },
    { id: 3, label: "Preset D" },
    { id: 4, label: "Default" },
  ],
  //  SAVE_MEM: [
  //    { id: 0, label: "Preset A" },
  //    { id: 1, label: "Preset B" },
  //    { id: 2, label: "Preset C" },
  //    { id: 3, label: "Preset D" },
  //  ],
  POWER: [
    { id: 0, label: "Off" },
    { id: 1, label: "On" },
  ],
  PIC_MUTE: [
    { id: 0, label: "Open" },
    { id: 1, label: "Close" },
  ],
  LASER_MODE: [
    { id: 0, label: "Eco" },
    { id: 1, label: "Normal" },
    { id: 2, label: "Custom" },
  ],
};
